# Generated by Django 5.1.5 on 2025-02-05 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='carName',
            field=models.CharField(default='Empty', max_length=100),
        ),
    ]
