# Generated by Django 5.2 on 2025-04-20 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_user2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User2',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='age',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='userName',
        ),
        migrations.RemoveField(
            model_name='user',
            name='carName',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
    ]
